---
name: Feature Request
description: Suggest a new feature for the project
title: "[Feature:] "
labels: ["enhancement"]
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: What is your name?
      placeholder: ex. Aphichaya Suppakitkumjorn
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: dropdown
    id: request-type
    attributes:
      label: Type of request?
      description: Select the type of your request
      options:
        - New Feature
        - Improvement
        - Other
  - type: textarea
    id: details
    attributes:
      label: What are the details of your suggestion?
      description: Explain what you want
      placeholder: Feature details!
---
